# SETUP

CLICK_INTERVAL = 50

# SCREEN

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 400
SCREEN_COLOR = 'lightgray'

# MAP

MAP_WIDTH = int(SCREEN_WIDTH * 0.8)
MAP_HEIGHT = int(SCREEN_HEIGHT * 0.8)
MAP_BEGIN_X = (SCREEN_WIDTH - MAP_WIDTH) // 2
MAP_BEGIN_Y = (SCREEN_HEIGHT - MAP_HEIGHT) // 2
MAP_RECT = (MAP_BEGIN_X, MAP_BEGIN_Y, MAP_WIDTH, MAP_HEIGHT)
MAP_COLOR = 'white'

# SCOREBOARD

SCOREBOARD_X = SCREEN_WIDTH // 2
SCOREBOARD_Y = MAP_BEGIN_Y // 2
SCOREBOARD_TEXT = 'Score: {} points'
SCOREBOARD_COLOR = 'black'

# GAME OVER

GAME_OVER_X = SCREEN_WIDTH // 2
GAME_OVER_Y = SCREEN_HEIGHT // 2
GAME_OVER_TEXT = 'GAME OVER'
GAME_OVER_COLOR = 'red'

# SNAKE

SNAKE_VELOCITY = 15
SNAKE_SIZE = int(min(SCREEN_WIDTH, SCREEN_HEIGHT) * 0.025)
SNAKE_COLOR = 'black'

# FOOD

FOOD_SIZE = SNAKE_SIZE // 2
FOOD_BEGIN_X = MAP_BEGIN_X + FOOD_SIZE
FOOD_END_X = MAP_BEGIN_X + MAP_WIDTH - FOOD_SIZE
FOOD_BEGIN_Y = MAP_BEGIN_Y + FOOD_SIZE
FOOD_END_Y = MAP_BEGIN_Y + MAP_HEIGHT - FOOD_SIZE
FOOD_COLOR = 'red'
